import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { parsePlaylistPage, parseResolvedChannelId } from "../src/browse.js";
import {
  cleanCaptionText,
  formatTimestamp,
  parseTimedText,
  segmentsToText,
  toSrt,
  toVtt,
} from "../src/captions.js";
import { InputError, normalizeInput } from "../src/input.js";
import {
  parseMicroformat,
  parsePlayer,
  selectTrack,
  timedTextUrl,
  type CaptionTrack,
} from "../src/player.js";
import {
  expandSource,
  ONLY_NEW_SEEN_STREAK,
  runTranscripts,
} from "../src/run.js";
import { Seen } from "../src/state.js";
import { parseSource, uploadsPlaylistId } from "../src/sources.js";
import { fetchTranscript, type TranscriptItem } from "../src/transcript.js";
import {
  BlockedError,
  YouTubeClient,
  type FetchFn,
  type HttpInit,
} from "../src/youtube.js";

const raw = (name: string) =>
  readFileSync(new URL(`./fixtures/${name}`, import.meta.url), "utf8");
const json = (name: string): unknown => JSON.parse(raw(name));

const PLAYER = json("player-android.json");
const MICRO = json("player-web-microformat.json");
const UNAVAILABLE = json("player-unavailable.json");
const TT_EN = raw("timedtext-en.xml");
const TT_ASR = raw("timedtext-asr.xml");
const BOT = {
  playabilityStatus: {
    status: "LOGIN_REQUIRED",
    reason: "Sign in to confirm you’re not a bot",
  },
};
const NO_CAPTIONS = { ...(PLAYER as object), captions: undefined };

interface Call {
  url: string;
  init: HttpInit;
  session: string;
  body: Record<string, unknown>;
}

type Reply = { status?: number; body: unknown; location?: string };
type Handler = (c: Call) => Reply | undefined;

/** Fake YouTube: routes requests to fixtures; `override` wins when it returns a reply. */
function fakeYouTube(override?: Handler) {
  const calls: Call[] = [];
  const fetch: FetchFn = async (url, init, session) => {
    const body = init.body ? JSON.parse(init.body) : {};
    const call = { url, init, session, body };
    calls.push(call);
    const r: Reply = override?.(call) ?? route(call);
    const text = typeof r.body === "string" ? r.body : JSON.stringify(r.body);
    return {
      status: r.status ?? 200,
      headers: { get: (h) => (h === "location" ? (r.location ?? null) : null) },
      text: async () => text,
    };
  };
  const route = (c: Call): Reply => {
    const client = (c.body.context as { client: { clientName: string } })
      ?.client?.clientName;
    if (c.url.includes("/player")) {
      if (client === "WEB") return { body: MICRO };
      if (c.body.videoId === "aaaaaaaaaaa") return { body: UNAVAILABLE };
      if (c.body.videoId === "nocaptions1") return { body: NO_CAPTIONS };
      return { body: PLAYER };
    }
    if (c.url.includes("/api/timedtext"))
      return { body: c.url.includes("kind=asr") ? TT_ASR : TT_EN };
    if (c.url.includes("/navigation/resolve_url"))
      return { body: json("resolve-url.json") };
    if (c.url.includes("/browse"))
      return {
        body: c.body.continuation
          ? json("browse-continuation.json")
          : json("browse-playlist.json"),
      };
    return { status: 404, body: "not found" };
  };
  const client = () =>
    new YouTubeClient({ fetch, backoffMs: 0, sleep: async () => {} });
  return { fetch, calls, client };
}

const OPTS = {
  languages: ["en"],
  allowAutoGenerated: true,
  fallbackToAnyLanguage: true,
  formats: ["text", "segments"] as ("text" | "segments" | "srt" | "vtt")[],
  includeMetadata: true,
};

describe("sources", () => {
  it("parses video URLs and IDs", () => {
    for (const u of [
      "dQw4w9WgXcQ",
      "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=10s",
      "youtube.com/watch?v=dQw4w9WgXcQ",
      "https://youtu.be/dQw4w9WgXcQ?si=abc",
      "https://m.youtube.com/watch?v=dQw4w9WgXcQ",
      "https://www.youtube.com/shorts/dQw4w9WgXcQ",
      "https://www.youtube.com/embed/dQw4w9WgXcQ",
      "https://www.youtube.com/live/dQw4w9WgXcQ",
      "https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ",
      "https://music.youtube.com/watch?v=dQw4w9WgXcQ&list=RDxyz",
    ]) {
      expect(parseSource(u)).toMatchObject({
        kind: "video",
        videoId: "dQw4w9WgXcQ",
      });
    }
  });

  it("parses playlists and channels", () => {
    expect(
      parseSource(
        "https://www.youtube.com/playlist?list=PLOGi5-fAu8bH_T9HhH9V2B5izEE4G5waV",
      ),
    ).toMatchObject({
      kind: "playlist",
      playlistId: "PLOGi5-fAu8bH_T9HhH9V2B5izEE4G5waV",
    });
    expect(parseSource("https://www.youtube.com/@TED/videos")).toMatchObject({
      kind: "channel",
      url: "https://www.youtube.com/@TED",
      tab: "videos",
    });
    expect(parseSource("@mkbhd")).toMatchObject({
      kind: "channel",
      tab: "all",
    });
    expect(
      parseSource(
        "https://www.youtube.com/channel/UCuAXFkgsw1L7xaCfnd5JJOw/shorts",
      ),
    ).toMatchObject({
      kind: "channel",
      channelId: "UCuAXFkgsw1L7xaCfnd5JJOw",
      tab: "shorts",
    });
    expect(parseSource("https://www.youtube.com/c/Foo")).toMatchObject({
      kind: "channel",
      url: "https://www.youtube.com/c/Foo",
    });
    expect(uploadsPlaylistId("UCuAXFkgsw1L7xaCfnd5JJOw", "all")).toBe(
      "UUuAXFkgsw1L7xaCfnd5JJOw",
    );
    expect(uploadsPlaylistId("UCuAXFkgsw1L7xaCfnd5JJOw", "videos")).toBe(
      "UULFuAXFkgsw1L7xaCfnd5JJOw",
    );
  });

  it("rejects non-YouTube input", () => {
    expect(() => parseSource("https://vimeo.com/123")).toThrow();
    expect(() => parseSource("hello world")).toThrow();
    expect(() => parseSource("https://www.youtube.com/watch?x=1")).toThrow();
  });
});

describe("input", () => {
  it("applies defaults", () => {
    const i = normalizeInput({});
    expect(i.sources).toHaveLength(2);
    expect(i.languages).toEqual(["en"]);
    expect(i.formats).toEqual(["text", "segments"]);
    expect(i.includeMetadata).toBe(true);
    expect(i.maxVideosPerSource).toBe(20);
  });

  it("dedupes and validates", () => {
    const i = normalizeInput({
      urls: ["dQw4w9WgXcQ", { url: "https://youtu.be/dQw4w9WgXcQ" }, " "],
      languages: ["en", "pt-BR", "en"],
      formats: ["SRT"],
      translateTo: "es",
    });
    expect(i.sources).toHaveLength(1);
    expect(i.languages).toEqual(["en", "pt-BR"]);
    expect(i.formats).toEqual(["srt"]);
    expect(i.translateTo).toBe("es");
    expect(() => normalizeInput({ urls: [] })).toThrow(InputError);
    expect(() => normalizeInput({ urls: ["nope nope"] })).toThrow(InputError);
    expect(() => normalizeInput({ formats: ["pdf"] })).toThrow(InputError);
    expect(() => normalizeInput({ languages: ["english!"] })).toThrow(
      InputError,
    );
  });
});

describe("captions", () => {
  it("decodes double-escaped entities and strips tags", () => {
    expect(cleanCaptionText("We&amp;#39;re no\nstrangers")).toBe(
      "We're no strangers",
    );
    expect(
      cleanCaptionText(
        "&lt;font color=&quot;#E5E5E5&quot;&gt;hi&lt;/font&gt; &amp;amp; bye",
      ),
    ).toBe("hi & bye");
  });

  it("parses manual and auto-generated timedtext", () => {
    const en = parseTimedText(TT_EN);
    expect(en.length).toBeGreaterThan(40);
    expect(en[1]).toEqual({
      start: 18.64,
      duration: 3.24,
      text: "♪ We're no strangers to love ♪",
    });
    const asr = parseTimedText(TT_ASR);
    expect(asr[1]!.text).toBe("We're no strangers to");
    expect(segmentsToText(asr)).toMatch(
      /^\[Music\] We're no strangers to love/,
    );
    expect(parseTimedText("<transcript></transcript>")).toEqual([]);
  });

  it("renders SRT and VTT with non-overlapping cues", () => {
    const segs = [
      { start: 0.32, duration: 14.26, text: "[Music]" },
      { start: 18.8, duration: 7.16, text: "We're no strangers to" },
      { start: 21.8, duration: 7.319, text: "love." },
    ];
    expect(toSrt(segs)).toBe(
      "1\n00:00:00,320 --> 00:00:14,580\n[Music]\n\n" +
        "2\n00:00:18,800 --> 00:00:21,800\nWe're no strangers to\n\n" +
        "3\n00:00:21,800 --> 00:00:29,119\nlove.\n",
    );
    expect(toVtt(segs)).toMatch(
      /^WEBVTT\n\n00:00:00\.320 --> 00:00:14\.580\n\[Music\]\n/,
    );
    expect(formatTimestamp(3723.5, ",")).toBe("01:02:03,500");
  });
});

describe("player", () => {
  it("parses tracks and metadata", () => {
    const p = parsePlayer(PLAYER);
    expect(p.playability).toBe("ok");
    expect(p.tracks.map((t) => t.languageCode)).toEqual([
      "en",
      "en",
      "de-DE",
      "ja",
      "pt-BR",
      "es-419",
    ]);
    expect(p.tracks[1]!.isAutoGenerated).toBe(true);
    expect(p.details).toMatchObject({
      title:
        "Rick Astley - Never Gonna Give You Up (Official Video) (4K Remaster)",
      channelName: "Rick Astley",
      channelId: "UCuAXFkgsw1L7xaCfnd5JJOw",
      durationSec: 213,
    });
    expect(p.details.viewCount).toBeGreaterThan(1e9);
    expect(p.translationLanguages.length).toBeGreaterThan(5);
    expect(parseMicroformat(MICRO)).toMatchObject({
      publishDate: "2009-10-24T23:57:33-07:00",
      category: "Music",
    });
  });

  it("classifies playability", () => {
    expect(parsePlayer(UNAVAILABLE).playability).toBe("unavailable");
    expect(parsePlayer(BOT).playability).toBe("botCheck");
    expect(
      parsePlayer({
        playabilityStatus: {
          status: "LOGIN_REQUIRED",
          reason: "This video is private",
        },
      }).playability,
    ).toBe("private");
    expect(
      parsePlayer({
        playabilityStatus: {
          status: "LOGIN_REQUIRED",
          reason: "Sign in to confirm your age",
        },
      }).playability,
    ).toBe("loginRequired");
  });

  it("selects tracks by preference", () => {
    const t = (languageCode: string, auto = false): CaptionTrack => ({
      languageCode,
      languageName: languageCode,
      isAutoGenerated: auto,
      isTranslatable: true,
      baseUrl: `https://www.youtube.com/api/timedtext?lang=${languageCode}&fmt=srv3`,
    });
    const tracks = [t("en", true), t("de-DE"), t("pt-BR"), t("fr", true)];
    const prefs = { allowAutoGenerated: true, fallbackToAnyLanguage: true };
    expect(selectTrack(tracks, { ...prefs, languages: ["de"] })).toBe(
      tracks[1],
    );
    expect(selectTrack(tracks, { ...prefs, languages: ["pt-BR"] })).toBe(
      tracks[2],
    );
    expect(selectTrack(tracks, { ...prefs, languages: ["en"] })).toBe(
      tracks[0],
    );
    expect(
      selectTrack(tracks, {
        ...prefs,
        languages: ["en"],
        allowAutoGenerated: false,
      }),
    ).toBe(tracks[1]);
    expect(selectTrack(tracks, { ...prefs, languages: ["ja"] })).toBe(
      tracks[1],
    );
    expect(
      selectTrack(tracks, {
        ...prefs,
        languages: ["ja"],
        fallbackToAnyLanguage: false,
      }),
    ).toBeUndefined();
    const url = new URL(timedTextUrl(tracks[0]!, "es"));
    expect(url.searchParams.get("fmt")).toBeNull();
    expect(url.searchParams.get("tlang")).toBe("es");
  });
});

describe("browse", () => {
  it("extracts playlist videos and continuation", () => {
    const p1 = parsePlaylistPage(json("browse-playlist.json"));
    expect(p1.videoIds).toHaveLength(100);
    expect(p1.continuation).toMatch(/^4qmF/);
    expect(p1.title).toBe("Uploads from Rick Astley");
    const p2 = parsePlaylistPage(json("browse-continuation.json"));
    expect(p2.videoIds).toHaveLength(100);
    expect(p2.videoIds.some((id) => p1.videoIds.includes(id))).toBe(false);
    expect(parseResolvedChannelId(json("resolve-url.json"))).toBe(
      "UCuAXFkgsw1L7xaCfnd5JJOw",
    );
  });

  it("expands a channel across pages up to max", async () => {
    const yt = fakeYouTube();
    const ids = await expandSource(
      yt.client(),
      parseSource("https://www.youtube.com/@RickAstleyYT"),
      150,
    );
    expect(ids).toHaveLength(150);
    const browse = yt.calls.filter((c) => c.url.includes("/browse"));
    expect(browse[0]!.body.browseId).toBe("VLUUuAXFkgsw1L7xaCfnd5JJOw");
    expect(browse[1]!.body.continuation).toBeTruthy();
  });
});

describe("client", () => {
  it("retries blocks with a fresh session, then gives up", async () => {
    let n = 0;
    const yt = fakeYouTube((c) =>
      c.url.includes("/player") && n++ < 2
        ? {
            status: 302,
            body: "",
            location: "https://www.google.com/sorry/index",
          }
        : undefined,
    );
    const client = yt.client();
    const p = parsePlayer(await client.player("dQw4w9WgXcQ", "ANDROID"));
    expect(p.playability).toBe("ok");
    const sessions = new Set(yt.calls.map((c) => c.session));
    expect(sessions.size).toBe(3);
    expect(client.stats.blocks).toBe(2);
    expect(yt.calls[0]!.init.headers!["X-Goog-FieldMask"]).toContain(
      "captions",
    );

    const always = fakeYouTube(() => ({ status: 429, body: "Too many" }));
    await expect(
      always.client().timedText("https://www.youtube.com/api/timedtext?v=x"),
    ).rejects.toBeInstanceOf(BlockedError);
    expect(always.calls).toHaveLength(4);
  });
});

describe("fetchTranscript", () => {
  it("returns transcript, segments and metadata", async () => {
    const yt = fakeYouTube();
    const item = await fetchTranscript(yt.client(), "dQw4w9WgXcQ", "src", {
      ...OPTS,
      formats: ["text", "segments", "srt", "vtt"],
    });
    expect(item).toMatchObject({
      videoId: "dQw4w9WgXcQ",
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      title:
        "Rick Astley - Never Gonna Give You Up (Official Video) (4K Remaster)",
      channelName: "Rick Astley",
      channelId: "UCuAXFkgsw1L7xaCfnd5JJOw",
      publishDate: "2009-10-24T23:57:33-07:00",
      durationSec: 213,
      language: "en",
      isAutoGenerated: false,
      isTranslated: false,
      error: null,
    });
    expect(item.transcript).toMatch(/^\[♪♪♪\] ♪ We're no strangers to love ♪/);
    expect(item.wordCount).toBeGreaterThan(300);
    expect(item.segments!.length).toBe(parseTimedText(TT_EN).length);
    expect(item.srt).toMatch(/^1\n00:00:01,360 --> /);
    expect(item.vtt).toMatch(/^WEBVTT/);
    expect(item.availableLanguages).toContainEqual({
      code: "en",
      name: "English (auto-generated)",
      isAutoGenerated: true,
    });
    const tt = yt.calls.find((c) => c.url.includes("timedtext"))!;
    expect(tt.url).not.toContain("fmt=");
  });

  it("uses auto-generated when manual is excluded, and translates", async () => {
    const yt = fakeYouTube();
    const client = yt.client();
    const auto = await fetchTranscript(client, "dQw4w9WgXcQ", "s", {
      ...OPTS,
      languages: ["en", "fr"],
      formats: ["text"],
      includeMetadata: false,
    });
    expect(auto.language).toBe("en");
    expect(auto.segments).toBeUndefined();
    expect(auto.channelName).toBeUndefined();
    const tr = await fetchTranscript(client, "dQw4w9WgXcQ", "s", {
      ...OPTS,
      translateTo: "fr",
      includeMetadata: false,
    });
    expect(tr).toMatchObject({
      language: "fr",
      languageName: "French",
      isTranslated: true,
    });
    expect(yt.calls.at(-1)!.url).toContain("tlang=fr");
    // A track already in the target language is used as-is.
    const pt = await fetchTranscript(client, "dQw4w9WgXcQ", "s", {
      ...OPTS,
      translateTo: "pt",
      includeMetadata: false,
    });
    expect(pt).toMatchObject({ language: "pt-BR", isTranslated: false });
  });

  it("returns error items for expected failures", async () => {
    const yt = fakeYouTube();
    const client = yt.client();
    const missing = await fetchTranscript(client, "aaaaaaaaaaa", "s", OPTS);
    expect(missing).toMatchObject({
      errorCode: "videoUnavailable",
      transcript: null,
    });
    const none = await fetchTranscript(client, "nocaptions1", "s", OPTS);
    expect(none).toMatchObject({
      errorCode: "noCaptions",
      title: expect.any(String),
    });
    const lang = await fetchTranscript(client, "dQw4w9WgXcQ", "s", {
      ...OPTS,
      languages: ["ko"],
      fallbackToAnyLanguage: false,
    });
    expect(lang.errorCode).toBe("languageNotAvailable");
    expect(lang.error).toContain("de-DE");
  });

  it("cycles clients on bot checks and throws when all fail", async () => {
    let bots = 2;
    const yt = fakeYouTube((c) =>
      c.url.includes("/player") && bots-- > 0 ? { body: BOT } : undefined,
    );
    const item = await fetchTranscript(yt.client(), "dQw4w9WgXcQ", "s", OPTS);
    expect(item.error).toBeNull();
    const clients = yt.calls
      .filter((c) => c.url.includes("/player"))
      .map(
        (c) =>
          (c.body.context as { client: { clientName: string } }).client
            .clientName,
      );
    expect(clients.slice(0, 3)).toEqual(["ANDROID", "ANDROID_VR", "IOS"]);

    const always = fakeYouTube((c) =>
      c.url.includes("/player") ? { body: BOT } : undefined,
    );
    await expect(
      fetchTranscript(always.client(), "dQw4w9WgXcQ", "s", OPTS),
    ).rejects.toBeInstanceOf(BlockedError);
  });
});

describe("runTranscripts", () => {
  it("expands sources, dedupes, charges only successes, stops at budget", async () => {
    const yt = fakeYouTube((c) =>
      c.url.includes("/player") && c.body.videoId === "UF8uR6Z6KLc"
        ? { body: BOT }
        : undefined,
    );
    const items: [TranscriptItem, boolean][] = [];
    const stats = await runTranscripts(
      normalizeInput({
        urls: [
          "dQw4w9WgXcQ",
          "aaaaaaaaaaa",
          "UF8uR6Z6KLc",
          "https://www.youtube.com/channel/UCuAXFkgsw1L7xaCfnd5JJOw",
          "https://www.youtube.com/@missing",
        ],
        maxVideosPerSource: 3,
        maxConcurrency: 2,
      }),
      {
        newClient: yt.client,
        emit: async (item, charge) => (items.push([item, charge]), true),
      },
    );
    expect(stats).toMatchObject({
      videos: 6,
      succeeded: 4,
      failed: 2,
      failures: { videoUnavailable: 1, blocked: 1 },
      stopReason: "done",
    });
    expect(stats.sourceErrors).toHaveLength(0);
    expect(items.filter(([, c]) => c)).toHaveLength(4);
    expect(items.filter(([i, c]) => c !== (i.error === null))).toHaveLength(0);

    let charged = 0;
    const budget = await runTranscripts(
      normalizeInput({
        urls: ["https://www.youtube.com/channel/UCuAXFkgsw1L7xaCfnd5JJOw"],
        maxVideosPerSource: 50,
      }),
      {
        newClient: yt.client,
        emit: async (_i, c) => (c ? ++charged < 3 : true),
      },
    );
    expect(budget.stopReason).toBe("budget");
    expect(charged).toBe(3);
  });

  it("onlyNew: skips videos returned before, retries failures", async () => {
    const CHANNEL = "https://www.youtube.com/channel/UCuAXFkgsw1L7xaCfnd5JJOw";
    const go = async (urls: string[], state: unknown, failId?: string) => {
      const yt = fakeYouTube((c) =>
        c.url.includes("/player") && c.body.videoId === failId
          ? { body: BOT }
          : undefined,
      );
      const seen = new Seen(state);
      const items: [TranscriptItem, boolean][] = [];
      const stats = await runTranscripts(
        normalizeInput({ urls, maxVideosPerSource: 3, onlyNew: true }),
        {
          newClient: yt.client,
          seen,
          emit: async (item, charge) => (items.push([item, charge]), true),
        },
      );
      const ok = items.filter(([, c]) => c).map(([i]) => i.videoId);
      return { ok, stats, state: seen.toJSON() };
    };
    const r1 = await go([CHANNEL, "UF8uR6Z6KLc"], undefined, "UF8uR6Z6KLc");
    expect(r1.ok).toHaveLength(3);
    // The 3 channel videos are known: the streak stops the channel; the
    // failed video is retried.
    const r2 = await go([CHANNEL, "UF8uR6Z6KLc"], r1.state);
    expect(r2.ok).toEqual(["UF8uR6Z6KLc"]);
    expect(r2.stats.skippedSeen).toBe(ONLY_NEW_SEEN_STREAK);
    const r3 = await go([CHANNEL, "UF8uR6Z6KLc"], r2.state);
    expect(r3.ok).toEqual([]);
    expect(r3.stats).toMatchObject({ videos: 0, sourceErrors: [] });
  });

  it("records source errors", async () => {
    const yt = fakeYouTube((c) =>
      c.url.includes("resolve_url") ? { body: { endpoint: {} } } : undefined,
    );
    const stats = await runTranscripts(normalizeInput({ urls: ["@nobody"] }), {
      newClient: yt.client,
      emit: async () => true,
    });
    expect(stats.videos).toBe(0);
    expect(stats.sourceErrors[0]).toContain("Channel not found");
  });
});
