import { parseSource, SourceError, type Source } from "./sources.js";

export const FORMATS = ["text", "segments", "srt", "vtt"] as const;
export type Format = (typeof FORMATS)[number];

/** Raw actor input, as defined in .actor/input_schema.json. */
export interface RawInput {
  urls?: (string | { url?: string })[];
  maxVideosPerSource?: number;
  languages?: string[];
  allowAutoGenerated?: boolean;
  fallbackToAnyLanguage?: boolean;
  translateTo?: string;
  formats?: string[];
  includeMetadata?: boolean;
  onlyNew?: boolean;
  proxyConfiguration?: unknown;
  maxConcurrency?: number;
}

export interface NormalizedInput {
  sources: Source[];
  maxVideosPerSource: number;
  languages: string[];
  allowAutoGenerated: boolean;
  fallbackToAnyLanguage: boolean;
  translateTo?: string;
  formats: Format[];
  includeMetadata: boolean;
  maxConcurrency: number;
  /** Skip videos whose transcript an earlier run returned (monitoring). */
  onlyNew: boolean;
}

export const DEFAULT_URLS = [
  "https://www.youtube.com/watch?v=UF8uR6Z6KLc",
  "https://youtu.be/dQw4w9WgXcQ",
];

export const DEFAULT_INPUT = {
  urls: DEFAULT_URLS,
  maxVideosPerSource: 20,
  languages: ["en"],
  allowAutoGenerated: true,
  fallbackToAnyLanguage: true,
  formats: ["text", "segments"],
  includeMetadata: true,
  maxConcurrency: 5,
} satisfies RawInput;

export const MAX_VIDEOS_PER_SOURCE_CAP = 5000;
export const MAX_CONCURRENCY_CAP = 20;

export class InputError extends Error {}

const LANG = /^[a-zA-Z]{2,3}(-[a-zA-Z0-9]{2,8})*$/;

const normLang = (v: unknown, name: string): string => {
  const s = String(v).trim();
  if (!LANG.test(s))
    throw new InputError(
      `${name}: "${s}" is not a language code (e.g. en, es, pt-BR).`,
    );
  return s;
};

const int = (v: unknown, name: string, def: number, min: number): number => {
  if (v === undefined || v === null || v === "") return def;
  const n = Math.floor(Number(v));
  if (!Number.isFinite(n) || n < min)
    throw new InputError(`${name} must be a number >= ${min}.`);
  return n;
};

export function normalizeInput(
  raw: RawInput | null | undefined,
): NormalizedInput {
  const r: RawInput = { ...DEFAULT_INPUT, ...(raw ?? {}) };

  if (!Array.isArray(r.urls)) throw new InputError("urls must be an array.");
  const sources: Source[] = [];
  const seen = new Set<string>();
  for (const u of r.urls) {
    const s = typeof u === "string" ? u : u?.url;
    if (typeof s !== "string" || !s.trim()) continue;
    let src: Source;
    try {
      src = parseSource(s);
    } catch (e) {
      if (e instanceof SourceError) throw new InputError(e.message);
      throw e;
    }
    const key =
      src.kind === "video"
        ? `v:${src.videoId}`
        : src.kind === "playlist"
          ? `p:${src.playlistId}`
          : `c:${src.channelId ?? src.url.toLowerCase()}:${src.tab}`;
    if (seen.has(key)) continue;
    seen.add(key);
    sources.push(src);
  }
  if (!sources.length)
    throw new InputError(
      "Add at least one YouTube video, channel or playlist URL.",
    );

  const languages = [
    ...new Set(
      (Array.isArray(r.languages) ? r.languages : [])
        .filter((l) => typeof l === "string" && l.trim())
        .map((l) => normLang(l, "languages")),
    ),
  ];
  const translateTo =
    typeof r.translateTo === "string" && r.translateTo.trim()
      ? normLang(r.translateTo, "translateTo")
      : undefined;

  const formats = [
    ...new Set(
      (Array.isArray(r.formats) ? r.formats : []).map((f) =>
        String(f).toLowerCase(),
      ),
    ),
  ];
  for (const f of formats) {
    if (!(FORMATS as readonly string[]).includes(f))
      throw new InputError(
        `Unknown format "${f}". Use: ${FORMATS.join(", ")}.`,
      );
  }

  return {
    sources,
    maxVideosPerSource: Math.min(
      int(
        r.maxVideosPerSource,
        "maxVideosPerSource",
        DEFAULT_INPUT.maxVideosPerSource,
        1,
      ),
      MAX_VIDEOS_PER_SOURCE_CAP,
    ),
    languages,
    allowAutoGenerated: r.allowAutoGenerated !== false,
    fallbackToAnyLanguage: r.fallbackToAnyLanguage !== false,
    translateTo,
    formats: (formats.length ? formats : ["text"]) as Format[],
    includeMetadata: r.includeMetadata !== false,
    maxConcurrency: Math.min(
      int(r.maxConcurrency, "maxConcurrency", DEFAULT_INPUT.maxConcurrency, 1),
      MAX_CONCURRENCY_CAP,
    ),
    onlyNew: r.onlyNew === true,
  };
}
