/** Pure parsing of InnerTube /player responses: playability, caption tracks and metadata. */

export interface CaptionTrack {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  isTranslatable: boolean;
  baseUrl: string;
}

export interface LanguageInfo {
  code: string;
  name: string;
  isAutoGenerated: boolean;
}

export type Playability =
  | "ok"
  | "unavailable"
  | "private"
  | "loginRequired"
  | "botCheck"
  | "unplayable";

export interface PlayerInfo {
  playability: Playability;
  reason?: string;
  tracks: CaptionTrack[];
  translationLanguages: { code: string; name: string }[];
  details: VideoDetails;
}

export interface VideoDetails {
  title: string | null;
  channelName: string | null;
  channelId: string | null;
  durationSec: number | null;
  viewCount: number | null;
  description: string | null;
  keywords: string[];
  thumbnailUrl: string | null;
  isLive: boolean | null;
}

export interface Microformat {
  publishDate: string | null;
  uploadDate: string | null;
  category: string | null;
  likeCount: number | null;
  description: string | null;
  channelUrl: string | null;
  isFamilySafe: boolean | null;
  isUnlisted: boolean | null;
}

type Json = Record<string, unknown>;
const obj = (v: unknown): Json =>
  v && typeof v === "object" && !Array.isArray(v) ? (v as Json) : {};
const arr = (v: unknown): unknown[] => (Array.isArray(v) ? v : []);
const str = (v: unknown): string | null =>
  typeof v === "string" && v ? v : null;
const num = (v: unknown): number | null => {
  if (v === undefined || v === null || v === "") return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
};

/** Text of `{simpleText}` or `{runs:[{text}]}`. */
export function textOf(v: unknown): string | null {
  const o = obj(v);
  if (typeof o.simpleText === "string") return o.simpleText;
  const runs = arr(o.runs);
  if (runs.length) return runs.map((r) => String(obj(r).text ?? "")).join("");
  if (typeof o.content === "string") return o.content;
  return null;
}

function playabilityOf(ps: Json): { p: Playability; reason?: string } {
  const status = str(ps.status) ?? "UNKNOWN";
  const reason =
    str(ps.reason) ??
    textOf(obj(obj(ps.errorScreen).playerErrorMessageRenderer).reason) ??
    undefined;
  const r = (reason ?? "").toLowerCase();
  if (status === "OK") return { p: "ok" };
  if (r.includes("not a bot") || r.includes("reloaded"))
    return { p: "botCheck", reason };
  if (status === "LOGIN_REQUIRED")
    return r.includes("private")
      ? { p: "private", reason }
      : { p: "loginRequired", reason };
  if (status === "ERROR") return { p: "unavailable", reason };
  return { p: "unplayable", reason: reason ?? status };
}

export function parsePlayer(json: unknown): PlayerInfo {
  const root = obj(json);
  const { p, reason } = playabilityOf(obj(root.playabilityStatus));
  const list = obj(obj(root.captions).playerCaptionsTracklistRenderer);
  const tracks: CaptionTrack[] = [];
  for (const t of arr(list.captionTracks)) {
    const o = obj(t);
    const baseUrl = str(o.baseUrl);
    const languageCode = str(o.languageCode);
    if (!baseUrl || !languageCode) continue;
    tracks.push({
      languageCode,
      languageName: textOf(o.name) ?? languageCode,
      isAutoGenerated: o.kind === "asr",
      isTranslatable: o.isTranslatable === true,
      baseUrl: baseUrl.startsWith("/")
        ? `https://www.youtube.com${baseUrl}`
        : baseUrl,
    });
  }
  const translationLanguages = arr(list.translationLanguages)
    .map((t) => ({
      code: str(obj(t).languageCode) ?? "",
      name: textOf(obj(t).languageName) ?? "",
    }))
    .filter((t) => t.code);

  const vd = obj(root.videoDetails);
  const thumbs = arr(obj(vd.thumbnail).thumbnails);
  const details: VideoDetails = {
    title: str(vd.title),
    channelName: str(vd.author),
    channelId: str(vd.channelId),
    durationSec: num(vd.lengthSeconds),
    viewCount: num(vd.viewCount),
    description:
      typeof vd.shortDescription === "string" ? vd.shortDescription : null,
    keywords: arr(vd.keywords).filter(
      (k): k is string => typeof k === "string",
    ),
    thumbnailUrl: str(obj(thumbs.at(-1)).url),
    isLive: typeof vd.isLiveContent === "boolean" ? vd.isLiveContent : null,
  };
  return { playability: p, reason, tracks, translationLanguages, details };
}

export function parseMicroformat(json: unknown): Microformat {
  const m = obj(obj(obj(json).microformat).playerMicroformatRenderer);
  const bool = (v: unknown) => (typeof v === "boolean" ? v : null);
  return {
    publishDate: str(m.publishDate),
    uploadDate: str(m.uploadDate),
    category: str(m.category),
    likeCount: num(m.likeCount),
    description: textOf(m.description),
    channelUrl: str(m.ownerProfileUrl),
    isFamilySafe: bool(m.isFamilySafe),
    isUnlisted: bool(m.isUnlisted),
  };
}

export interface TrackPrefs {
  languages: string[];
  allowAutoGenerated: boolean;
  fallbackToAnyLanguage: boolean;
}

const base = (code: string) => code.toLowerCase().split("-")[0]!;

/**
 * Pick a caption track: for each preferred language in order, a manual track
 * (exact code, then same base language), then an auto-generated one. Falls
 * back to the first manual, then first auto-generated track.
 */
export function selectTrack(
  tracks: CaptionTrack[],
  prefs: TrackPrefs,
): CaptionTrack | undefined {
  const pool = prefs.allowAutoGenerated
    ? tracks
    : tracks.filter((t) => !t.isAutoGenerated);
  for (const lang of prefs.languages) {
    const l = lang.toLowerCase();
    for (const auto of [false, true]) {
      const kind = pool.filter((t) => t.isAutoGenerated === auto);
      const hit =
        kind.find((t) => t.languageCode.toLowerCase() === l) ??
        kind.find((t) => base(t.languageCode) === base(l));
      if (hit) return hit;
    }
  }
  if (!prefs.fallbackToAnyLanguage && prefs.languages.length) return undefined;
  return pool.find((t) => !t.isAutoGenerated) ?? pool[0];
}

export const sameLanguage = (a: string, b: string) =>
  a.toLowerCase() === b.toLowerCase() || base(a) === base(b);

/** Timedtext URL for a track (srv1 XML), optionally machine-translated. */
export function timedTextUrl(
  track: CaptionTrack,
  translateTo?: string,
): string {
  const u = new URL(track.baseUrl);
  u.searchParams.delete("fmt");
  if (translateTo) u.searchParams.set("tlang", translateTo);
  return u.toString();
}

export const languagesOf = (tracks: CaptionTrack[]): LanguageInfo[] =>
  tracks.map((t) => ({
    code: t.languageCode,
    name: t.languageName,
    isAutoGenerated: t.isAutoGenerated,
  }));
