import {
  parseTimedText,
  segmentsToText,
  toSrt,
  toVtt,
  type Segment,
} from "./captions.js";
import type { Format } from "./input.js";
import {
  languagesOf,
  parseMicroformat,
  parsePlayer,
  sameLanguage,
  selectTrack,
  timedTextUrl,
  type LanguageInfo,
  type Microformat,
  type PlayerInfo,
  type TrackPrefs,
} from "./player.js";
import { videoUrl } from "./sources.js";
import { BlockedError, PLAYER_CLIENTS, type YouTubeClient } from "./youtube.js";

export type ErrorCode =
  | "noCaptions"
  | "languageNotAvailable"
  | "translationNotAvailable"
  | "emptyTranscript"
  | "videoUnavailable"
  | "privateVideo"
  | "loginRequired"
  | "blocked"
  | "requestFailed";

export interface TranscriptItem {
  videoId: string;
  url: string;
  title: string | null;
  channelName?: string | null;
  channelId?: string | null;
  channelUrl?: string | null;
  publishDate?: string | null;
  durationSec?: number | null;
  viewCount?: number | null;
  likeCount?: number | null;
  category?: string | null;
  keywords?: string[];
  description?: string | null;
  thumbnailUrl?: string | null;
  language: string | null;
  languageName: string | null;
  isAutoGenerated: boolean | null;
  isTranslated: boolean;
  availableLanguages: LanguageInfo[];
  transcript?: string | null;
  wordCount?: number;
  segments?: Segment[];
  srt?: string;
  vtt?: string;
  /** The input URL/ID this video came from. */
  source: string;
  error: string | null;
  errorCode: ErrorCode | null;
}

export interface TranscriptOptions extends TrackPrefs {
  translateTo?: string;
  formats: Format[];
  includeMetadata: boolean;
  log?: (msg: string) => void;
}

const PLAYABILITY_ERRORS: Record<string, ErrorCode> = {
  unavailable: "videoUnavailable",
  private: "privateVideo",
  loginRequired: "loginRequired",
  unplayable: "videoUnavailable",
  botCheck: "blocked",
};

function metadataFields(
  info: PlayerInfo | undefined,
  mf: Microformat | undefined,
  include: boolean,
): Partial<TranscriptItem> {
  const d = info?.details;
  if (!include) return { title: d?.title ?? null };
  return {
    title: d?.title ?? null,
    channelName: d?.channelName ?? null,
    channelId: d?.channelId ?? null,
    channelUrl:
      mf?.channelUrl ??
      (d?.channelId ? `https://www.youtube.com/channel/${d.channelId}` : null),
    publishDate: mf?.publishDate ?? mf?.uploadDate ?? null,
    durationSec: d?.durationSec ?? null,
    viewCount: d?.viewCount ?? null,
    likeCount: mf?.likeCount ?? null,
    category: mf?.category ?? null,
    keywords: d?.keywords ?? [],
    description: d?.description ?? mf?.description ?? null,
    thumbnailUrl: d?.thumbnailUrl ?? null,
  };
}

/** Item for a video that produced no transcript (never charged). */
export function errorItem(
  videoId: string,
  source: string,
  code: ErrorCode,
  message: string,
  info?: PlayerInfo,
  mf?: Microformat,
  includeMetadata = true,
): TranscriptItem {
  return {
    videoId,
    url: videoUrl(videoId),
    title: null,
    ...metadataFields(info, mf, includeMetadata),
    language: null,
    languageName: null,
    isAutoGenerated: null,
    isTranslated: false,
    availableLanguages: info ? languagesOf(info.tracks) : [],
    transcript: null,
    source,
    error: message,
    errorCode: code,
  };
}

export const PLAYER_ATTEMPTS = 5;

async function loadPlayer(
  yt: YouTubeClient,
  videoId: string,
  log: (m: string) => void,
): Promise<PlayerInfo> {
  let info: PlayerInfo | undefined;
  // Bot checks are per exit IP: cycle clients and rotate the proxy session.
  for (let i = 0; i < PLAYER_ATTEMPTS; i++) {
    const client = PLAYER_CLIENTS[i % PLAYER_CLIENTS.length]!;
    info = parsePlayer(await yt.player(videoId, client));
    if (info.playability === "ok") return info;
    if (info.playability === "botCheck") {
      log(`${videoId}: ${client} bot check ("${info.reason}"), new session`);
      yt.rotateSession();
      continue;
    }
    if (info.playability === "unplayable") continue;
    return info; // unavailable / private / login required: final
  }
  return info!;
}

/**
 * Fetch one video's transcript. Expected failures (no captions, private
 * video, ...) return an item with `error`; transport failures throw.
 */
export async function fetchTranscript(
  yt: YouTubeClient,
  videoId: string,
  source: string,
  opts: TranscriptOptions,
): Promise<TranscriptItem> {
  const log = opts.log ?? (() => {});
  const info = await loadPlayer(yt, videoId, log);

  let mf: Microformat | undefined;
  const loadMicroformat = async () => {
    if (!opts.includeMetadata) return;
    try {
      mf = parseMicroformat(await yt.microformat(videoId));
    } catch (e) {
      log(`${videoId}: metadata lookup failed: ${(e as Error).message}`);
    }
  };
  const fail = async (code: ErrorCode, msg: string) => {
    if (info.playability === "ok") await loadMicroformat();
    return errorItem(
      videoId,
      source,
      code,
      msg,
      info,
      mf,
      opts.includeMetadata,
    );
  };

  if (info.playability !== "ok") {
    const code = PLAYABILITY_ERRORS[info.playability] ?? "videoUnavailable";
    const msg = info.reason ?? "Video is not available.";
    if (code === "blocked") throw new BlockedError(`player: ${msg}`);
    return fail(code, msg);
  }
  if (!info.tracks.length)
    return fail("noCaptions", "This video has no captions or subtitles.");

  const languages = opts.translateTo
    ? [opts.translateTo, ...opts.languages]
    : opts.languages;
  const track = selectTrack(info.tracks, {
    languages,
    allowAutoGenerated: opts.allowAutoGenerated,
    fallbackToAnyLanguage: opts.fallbackToAnyLanguage || !!opts.translateTo,
  });
  if (!track) {
    const avail = languagesOf(info.tracks)
      .map((l) => `${l.code}${l.isAutoGenerated ? " (auto)" : ""}`)
      .join(", ");
    return fail(
      "languageNotAvailable",
      `No captions in ${languages.join(", ")}${opts.allowAutoGenerated ? "" : " (manual only)"}. Available: ${avail}.`,
    );
  }

  let translate: string | undefined;
  if (opts.translateTo && !sameLanguage(track.languageCode, opts.translateTo)) {
    if (!track.isTranslatable)
      return fail(
        "translationNotAvailable",
        `YouTube cannot translate the ${track.languageName} track to ${opts.translateTo}.`,
      );
    translate = opts.translateTo;
  }

  const xml = await yt.timedText(timedTextUrl(track, translate));
  const segments = parseTimedText(xml);
  if (!segments.length)
    return fail("emptyTranscript", "YouTube returned an empty caption track.");
  await loadMicroformat();

  const text = segmentsToText(segments);
  const translatedName = translate
    ? (info.translationLanguages.find((l) => sameLanguage(l.code, translate))
        ?.name ?? translate)
    : undefined;
  const item: TranscriptItem = {
    videoId,
    url: videoUrl(videoId),
    title: null,
    ...metadataFields(info, mf, opts.includeMetadata),
    language: translate ?? track.languageCode,
    languageName: translatedName ?? track.languageName,
    isAutoGenerated: track.isAutoGenerated,
    isTranslated: !!translate,
    availableLanguages: languagesOf(info.tracks),
    source,
    error: null,
    errorCode: null,
  };
  if (opts.formats.includes("text")) {
    item.transcript = text;
    item.wordCount = text.split(/\s+/).filter(Boolean).length;
  }
  if (opts.formats.includes("segments")) item.segments = segments;
  if (opts.formats.includes("srt")) item.srt = toSrt(segments);
  if (opts.formats.includes("vtt")) item.vtt = toVtt(segments);
  return item;
}
