/**
 * Live smoke test against YouTube (no Apify platform needed).
 * Runs the default input, a channel expansion with SRT/VTT, a missing video
 * and a translation, and validates every transcript that comes back.
 *
 * YouTube bot-checks many datacenter IPs. Videos that come back with
 * errorCode "blocked" are reported as BLOCKED and skipped (parsing is covered
 * by the fixture tests); set SMOKE_STRICT=1 to fail on them instead.
 * Set SMOKE_PROXY_URL=http://user:pass@host:port to route through a proxy.
 * Usage: npm run smoke -w actors/youtube-transcripts
 */
import { makeFetch } from "../src/http.js";
import { normalizeInput } from "../src/input.js";
import { runTranscripts } from "../src/run.js";
import type { TranscriptItem } from "../src/transcript.js";
import { YouTubeClient } from "../src/youtube.js";

const proxyUrl = process.env.SMOKE_PROXY_URL;
const fetchFn = makeFetch(
  proxyUrl ? { newUrl: async () => proxyUrl } : undefined,
);
const newClient = () =>
  new YouTubeClient({ fetch: fetchFn, log: (m) => console.warn(`  ${m}`) });

const problems: string[] = [];
const blocked: string[] = [];
let succeeded = 0;

async function run(label: string, raw: Parameters<typeof normalizeInput>[0]) {
  const out: TranscriptItem[] = [];
  const started = Date.now();
  const stats = await runTranscripts(normalizeInput(raw), {
    newClient,
    emit: async (item) => (out.push(item), true),
  });
  const seconds = (Date.now() - started) / 1000;
  console.log(`\n== ${label}: ${JSON.stringify({ ...stats, seconds })}`);
  for (const i of out) {
    console.log(
      `  ${i.videoId} ${i.error ? `ERROR ${i.errorCode}: ${i.error.slice(0, 120)}` : `${i.language}${i.isAutoGenerated ? " (auto)" : ""}${i.isTranslated ? " (translated)" : ""} ${i.segments?.length ?? "-"} segments, ${i.wordCount ?? "-"} words | ${i.title} | ${i.channelName} | ${i.publishDate} | ${i.durationSec}s | ${i.viewCount} views`}`,
    );
    if (i.errorCode === "blocked") blocked.push(`${label}: ${i.videoId}`);
    if (!i.error) succeeded += 1;
  }
  problems.push(...stats.sourceErrors);
  return { out, seconds };
}

const checkTranscript = (i: TranscriptItem, needMeta: boolean) => {
  if (!i.transcript || i.transcript.length < 200)
    problems.push(`${i.videoId}: transcript too short`);
  if (i.transcript && /&(#\d+|#x[0-9a-f]+|amp|quot|lt|gt);/i.test(i.transcript))
    problems.push(`${i.videoId}: undecoded entities`);
  if (
    needMeta &&
    (!i.title || !i.channelId || !i.publishDate || !i.durationSec)
  )
    problems.push(`${i.videoId}: missing metadata`);
};

// 1. Default input (what Apify's daily test runs).
const def = await run("default input", {});
if (def.seconds > 45) problems.push(`default input took ${def.seconds}s`);
for (const i of def.out) {
  if (i.errorCode === "blocked") continue;
  if (i.error) problems.push(`${i.videoId}: ${i.error}`);
  else {
    checkTranscript(i, true);
    if (!i.segments?.length || i.segments.some((s) => !(s.start >= 0)))
      problems.push(`${i.videoId}: bad segments`);
  }
}

// 2. Channel expansion, SRT/VTT, and a video that doesn't exist.
const ch = await run("channel + srt/vtt + missing video", {
  urls: [
    "https://www.youtube.com/@TED/videos",
    "aaaaaaaaaaa",
    "https://www.youtube.com/shorts/dQw4w9WgXcQ",
  ],
  maxVideosPerSource: 2,
  formats: ["text", "srt", "vtt"],
  includeMetadata: false,
});
if (ch.out.length !== 4)
  problems.push(`channel: expected 4 items, got ${ch.out.length}`);
for (const i of ch.out) {
  if (i.videoId === "aaaaaaaaaaa") {
    if (i.errorCode !== "videoUnavailable")
      problems.push(`missing video: got ${i.errorCode}`);
  } else if (!i.error) {
    checkTranscript(i, false);
    if (!i.srt?.startsWith("1\n") || !i.vtt?.startsWith("WEBVTT"))
      problems.push(`${i.videoId}: bad srt/vtt`);
  } else if (i.errorCode !== "blocked") {
    problems.push(`${i.videoId}: ${i.error}`);
  }
}

// 3. Machine translation (tlang) of an English track to French.
const tr = await run("translation en -> fr", {
  urls: ["dQw4w9WgXcQ"],
  languages: ["en"],
  translateTo: "fr",
  includeMetadata: false,
});
for (const i of tr.out) {
  if (i.errorCode === "blocked") continue;
  if (i.error) problems.push(`translation: ${i.error}`);
  else if (!i.isTranslated || i.language !== "fr")
    problems.push(
      `translation: got ${i.language}, translated=${i.isTranslated}`,
    );
}

if (blocked.length) {
  console.warn(
    `\nBLOCKED: YouTube bot-checked/rate-limited this machine's IP for ${blocked.length} video(s): ${blocked.join(", ")}.` +
      "\nThese were skipped; the fixture tests cover parsing. On Apify, use the RESIDENTIAL proxy (the default).",
  );
  if (process.env.SMOKE_STRICT) problems.push("blocked (SMOKE_STRICT)");
}
if (!succeeded) problems.push("no transcript succeeded at all");
if (problems.length) {
  console.error("SMOKE FAILED", problems);
  process.exit(1);
}
console.log(
  `\nSMOKE OK (${succeeded} transcripts verified live${blocked.length ? `, ${blocked.length} blocked` : ""})`,
);
